#!/usr/bin/env node
'use strict';

// Pulls the live wolffconstruction.com design tokens into the console.
// Run this on a machine with normal internet (the client site blocks some
// proxies):
//
//   node scripts/brand-sync.js
//
// It fetches the homepage and its stylesheets, extracts font families and
// the color palette, writes data/brand.json for review, and generates
// app/public/brand.css which overrides the console's default tokens.
// Review data/brand.json before committing; heuristics guess, humans decide.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SITE = 'https://www.wolffconstruction.com/';
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

async function get(url) {
  const res = await fetch(url, { headers: { 'user-agent': UA, accept: 'text/html,text/css,*/*' } });
  if (!res.ok) throw new Error(`${url} -> ${res.status}`);
  return res.text();
}

(async () => {
  const html = await get(SITE);

  // Stylesheets: linked CSS plus inline <style> blocks (Duda inlines a lot).
  const cssUrls = [...html.matchAll(/<link[^>]+rel=["']stylesheet["'][^>]*href=["']([^"']+)["']/gi)]
    .map((m) => new URL(m[1], SITE).href);
  const inline = [...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)].map((m) => m[1]);
  const sheets = [...inline];
  for (const u of cssUrls) {
    try { sheets.push(await get(u)); } catch (e) { console.warn(`skip ${u}: ${e.message}`); }
  }
  const css = sheets.join('\n');

  // Fonts: Google Fonts links first (ground truth), then font-family tallies.
  const gfonts = [...html.matchAll(/fonts\.googleapis\.com\/css2?\?[^"']*family=([^"'&]+)/gi)]
    .flatMap((m) => decodeURIComponent(m[1]).split('|'))
    .map((f) => f.split(':')[0].replace(/\+/g, ' '));
  const famTally = {};
  for (const m of css.matchAll(/font-family\s*:\s*([^;}]+)/gi)) {
    const fam = m[1].split(',')[0].replace(/["']/g, '').trim();
    if (fam && !/inherit|initial|sans-serif|serif|monospace/i.test(fam)) famTally[fam] = (famTally[fam] || 0) + 1;
  }
  const families = Object.entries(famTally).sort((a, b) => b[1] - a[1]).map(([f, n]) => ({ family: f, uses: n }));

  // Colors: tally hex values, split into darks (ink candidates), lights
  // (ground candidates), and saturated warms (accent candidates).
  const tally = {};
  for (const m of css.matchAll(/#([0-9a-f]{6}|[0-9a-f]{3})\b/gi)) {
    const h = m[1].length === 3 ? m[1].split('').map((c) => c + c).join('') : m[1];
    tally['#' + h.toLowerCase()] = (tally['#' + h.toLowerCase()] || 0) + 1;
  }
  const colors = Object.entries(tally).sort((a, b) => b[1] - a[1]).slice(0, 40)
    .map(([hex, uses]) => {
      const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
      const lum = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
      const sat = (Math.max(r, g, b) - Math.min(r, g, b)) / 255;
      return { hex, uses, lum: +lum.toFixed(2), sat: +sat.toFixed(2), warm: r >= b };
    });

  const ink = colors.find((c) => c.lum < 0.25) || null;
  const ground = colors.find((c) => c.lum > 0.93) || null;
  const accent = colors.filter((c) => c.sat > 0.15 && c.lum > 0.25 && c.lum < 0.8 && c.warm)
    .sort((a, b) => b.uses - a.uses)[0] || null;

  const brand = {
    fetchedFrom: SITE,
    fetchedAt: new Date().toISOString(),
    googleFonts: [...new Set(gfonts)],
    fontFamilies: families.slice(0, 10),
    palette: colors.slice(0, 20),
    guess: {
      display: gfonts[0] || families[0]?.family || null,
      body: gfonts[1] || families[1]?.family || families[0]?.family || null,
      ink: ink?.hex || null,
      ground: ground?.hex || null,
      accent: accent?.hex || null,
    },
    note: 'Heuristic extraction. Confirm guesses against the live site, then keep or edit brand.css.',
  };
  fs.writeFileSync(path.join(ROOT, 'data', 'brand.json'), JSON.stringify(brand, null, 2) + '\n');

  const g = brand.guess;
  const importLine = brand.googleFonts.length
    ? `@import url('https://fonts.googleapis.com/css2?${brand.googleFonts.map((f) => 'family=' + f.replace(/ /g, '+') + ':wght@300;400;500;600').join('&')}&display=swap');\n`
    : '';
  fs.writeFileSync(path.join(ROOT, 'app', 'public', 'brand.css'),
`/* Generated by scripts/brand-sync.js from ${SITE} on ${brand.fetchedAt.slice(0, 10)}.
   Review data/brand.json; edit or regenerate, do not let this drift by hand. */
${importLine}:root {
${g.display ? `  --display: '${g.display}', var(--sans);\n` : ''}${g.body ? `  --sans: '${g.body}', -apple-system, 'Segoe UI', Arial, sans-serif;\n` : ''}${g.ink ? `  --ink: ${g.ink};\n` : ''}${g.accent ? `  --brass: ${g.accent};\n` : ''}}
`);

  console.log('Fonts found:', brand.googleFonts.join(', ') || families.slice(0, 3).map((f) => f.family).join(', ') || 'none detected');
  console.log('Guess:', JSON.stringify(g));
  console.log('Wrote data/brand.json and app/public/brand.css. Restart the app to see it.');
})().catch((e) => { console.error(e.message); process.exit(1); });
